### PR TITLE
sostat: check for stuck ELSA cron.pl

### PR DESCRIPTION
**Pull request by weslambert**
Related to : https://github.com/Security-Onion-Solutions/security-onion/issues/1061

Modified sostat/sostat-redacted to look for multiple cron.pl processes.  If found, sostat will alert the user and grep the ELSA web.log file for error messages.

Also modified sostat with an "a" flag (Ex. sudo sostat -a), for showing all installed Security Onion packages.

Please let me know if/how it could be improved.

Thanks,
Wes

### CODE REVIEW

**Comment by dougburks** [comment]
Thanks, Wes!  I'll take a look at this in March.

**Comment by weslambert** [comment]
Added commit in reference to : https://github.com/Security-Onion-Solutions/security-onion/issues/1021

**Comment by dougburks** [comment]
Thanks, Wes!

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/de_uJ652_jY/discussion

**Pull request merged**
